EZP-27696: Dashboard framework with pagination support
ezsystems/hybrid-platform-ui pull request #104
Opened 2017-08-29 09:53 UTC by Nattfarinn

Dashboard framework only.

2017-08-30 12:08 UTC, dpobel requested changes
in addition to inline comments, it would be nice to unit test the Dashboard class

2017-08-30 12:08 UTC, dpobel commented on src/bundle/DependencyInjection/EzSystemsHybridPlatformUiExtension.php
> +                    'non_siteaccess_aware_routes' => [
why do you make this route not siteaccess aware ?

2017-08-30 12:08 UTC, dpobel commented on src/bundle/Resources/config/navigationhub.yml
> +            - "ez_hybrid_platform_ui_dashboard"
hum, I think there's a confusion here. This changes basically replaces the *admin* Dashboard (the one accessible in Admin / Dashboard)  by the dashboard you are implementing here which is supposed to be visible right after login or by clicking on the eZ logo in the top left corner of the UI. Unless, this was asked by PM (and I failed to find anything related to that), we should keep the admin dashboard

2017-08-30 12:08 UTC, dpobel commented on src/bundle/Resources/public/css/modules/table-data.css
> +.ez-dashboard-tabs .ez-table-data thead tr {
the CSS should not be in that PR, especially because it refers to some markup which is not added yet

2017-08-30 12:08 UTC, dpobel commented on src/bundle/Resources/views/dashboard.html.twig
> -    <h1>Dashboard</h1>
according to the screenshot in the EPIC, you should actually replace that with something like:
```html
<header class="ez-page-header">
    <h1>{{ 'my.dashboard'|trans({}, 'dashboard')|desc('My Dashboard') }}</h1>
</header>
```

2017-08-30 12:08 UTC, dpobel commented on src/lib/Dashboard/PaginatedTab.php
> +    public function render($page = 1): string
the `$page` is not used and is not defined the TabInterface ?

2017-08-30 12:08 UTC, dpobel commented on src/lib/Dashboard/PaginatedTab.php
> +    protected function getPaginatorUrls(int $current, int $last): array
With `getPageUrl`, this does not seem to be used anywhere yet, so better to not include that just yet (also I find the implementation a bit weird but it's hard to understand everything without an example of use ;))

2017-09-01 13:10 UTC, glye reviewed
(Some notes added, but I'm uncertain about them, so not making this a change request)

2017-09-01 13:10 UTC, glye commented on src/lib/Dashboard/Dashboard.php
> +class Dashboard
Unsure, but this whole class is quite basic and looks like something we or even Symfony ought to have standard code for. Wondering if `ValueObject` or somesuch could be used...? Same for `PaginatedTab` and `TabsSection`.

2017-09-01 13:10 UTC, glye commented on src/lib/Dashboard/SectionInterface.php
> +interface SectionInterface
This is the same as `TabInterface`. They are small, but could we reduce duplication by having a common top level interface, or a `Renderable` trait, maybe?

2017-09-01 13:10 UTC, glye commented on src/lib/Dashboard/TabInterface.php
> +interface TabInterface
This is the same as `SectionInterface`. They are small, but could we reduce duplication by having a common top level interface, or a `Renderable` trait, maybe?
Also, missing method doc.

2017-11-15 09:47 UTC, closed without merging