[WIP] Hybrid architecture basics
ezsystems/hybrid-platform-ui pull request #2
Opened 2017-04-05 15:41 UTC by bdunogier

This is a work in progress of the initial version of the package. It will include:
- the hybrid app/component architecture
- toolbars
- navigation hub
- location view
- dashboard
- pjax / admin modules integration

2017-04-06 08:25 UTC, dpobel commented on src/lib/Mapper/PjaxResponseMainContentMapper.php
> +            $this->innerHtml($contentNode) .
this feels a bit complicated and scary but I like the `innerHtml` method ;)

Joke aside, why not just wrap the content of `div[@data-name="html"]` in `<div class="ez-view-serversideview"></div>` ?

2017-05-04 10:05 UTC, lolautruche commented on src/bundle/DependencyInjection/Compiler/NavigationHubPass.php
> +            ->getDefinition('ezsystems.platformui.component.navigationhub')
Prefer `findDefinition()` as this will also look for aliases (better extensibility)

2017-05-04 10:05 UTC, lolautruche commented on src/bundle/DependencyInjection/Compiler/ToolbarsPass.php
> +            ->getDefinition('ezsystems.platformui.component.app')
`findDefinition()`

2017-05-04 10:05 UTC, lolautruche commented on src/bundle/DependencyInjection/Configuration.php
> +}
If you don't define any semantic config, better remove it and its reference in DIC extension

2017-05-04 10:05 UTC, lolautruche commented on src/bundle/Resources/config/components.yml
> +        shared: false
Are thoses services intended to be public (i.e. accessible directly from container)?
If not, you really should mark them as `public: false`

2017-05-04 10:05 UTC, lolautruche commented on src/bundle/Resources/config/navigationhub.yml
> +            - {name: ezplatform.ui.link}
I guess these services should be marked `public: false`

2017-05-04 10:05 UTC, lolautruche commented on src/bundle/Resources/config/navigationhub.yml
> +    ezsystems.platformui.navigationhub.link.subtree.class: EzSystems\HybridPlatformUi\NavigationHub\Link\Subtree
Class parameters are deprecated.

2017-05-04 10:05 UTC, lolautruche commented on src/bundle/Resources/config/services.yml
> +            - "@ezsystems.platformui.component.maincontent"
Same remark about public services.
Please note that event subscribers must be public though.

2017-05-04 10:05 UTC, lolautruche commented on src/bundle/Resources/config/toolbars.yml
> +
Extra empty line

2017-05-04 10:05 UTC, lolautruche commented on src/bundle/Resources/views/layout.html.twig
> +    <link rel="import" href="{{ asset( 'bundles/ezplatformui/webcomponents/ez-universaldiscoverywidget.html' ) }}">
Soon with `ezdesign` package to use with themes 😝

2017-05-04 10:05 UTC, lolautruche commented on src/lib/App/AppResponseRenderer.php
> +interface AppResponseRenderer
Maybe a little PHP doc to describe its role and when it's supposed to be used?

2017-05-04 10:05 UTC, lolautruche commented on src/lib/App/RequestAppResponseRenderer.php
> +        $appResponse = $this->ajaxUpdateRequestMatcher->matches($this->requestStack->getMasterRequest())
If you only need the master request, then inject it with an expression: `'@=service("request_stack").masterRequest'`

2017-05-04 10:05 UTC, lolautruche commented on src/lib/Components/App.php
> +        $templating,
No type hint?

2017-05-04 10:05 UTC, lolautruche commented on src/lib/Components/App.php
> +    protected $title;
Unless this class is supposed to be extended via inheritance, visibility should be `private`

2017-05-04 10:05 UTC, lolautruche commented on src/lib/Components/Browse.php
> +    protected $request;
Should be `private`

2017-05-04 10:05 UTC, lolautruche commented on src/lib/Components/Browse.php
> +        $this->request = $stack->getMasterRequest();
Inject master request directly instead, and rename the variable/property

2017-05-04 10:05 UTC, lolautruche commented on src/lib/Components/Browse.php
> +    protected function getLocationRestId()
`private` (same everywhere `protected` visibility is used, unless really needed).

2017-05-04 10:05 UTC, lolautruche commented on src/lib/Components/Browse.php
> +    public function __construct(RequestStack $stack, RouterInterface $router)
Since you're only using `$router` to generate URLs, you should then typehint against `UrlGeneratorInterface` instead.

2017-05-04 10:05 UTC, lolautruche commented on src/lib/Components/Component.php
> +interface Component extends \JsonSerializable
Missing PHPDoc

2017-05-04 10:05 UTC, lolautruche commented on src/lib/App/RequestAppResponseRenderer.php
> +        $appResponse = $this->ajaxUpdateRequestMatcher->matches($this->requestStack->getMasterRequest())
Same everywhere else

2017-05-04 10:05 UTC, lolautruche commented on src/lib/Components/MainContent.php
> +    public function __construct($templating)
Typehint?

2017-05-04 10:05 UTC, lolautruche commented on src/lib/Components/NavigationHub.php
> +    public function __construct($templating, RequestStack $stack, array $zones = [], array $links = [])
typehint

2017-05-04 10:05 UTC, lolautruche commented on src/lib/Components/NavigationHub.php
> +                'tag' => self::TAG_NAME,
better use `static`.
Note that `self` will be deprecated soon in PHP

2017-05-04 10:05 UTC, lolautruche commented on src/lib/Components/NavigationHub.php
> +                'tag' => self::TAG_NAME,
Same everywhere else, at least for class constants

2017-05-04 10:05 UTC, lolautruche commented on src/lib/EventSubscriber/AppRendererSubscriber.php
> +        if ($event->getRequestType() !== HttpKernelInterface::MASTER_REQUEST) {
You can now use `$event->isMasterRequest()`

2017-05-04 10:05 UTC, lolautruche commented on src/lib/EventSubscriber/AppRendererSubscriber.php
> +        $this->appRenderer->render($event->getResponse(), $this->app);
`render()` method name might be confusing/misleading. Does it return or display content?

2017-05-04 10:05 UTC, lolautruche commented on src/lib/NavigationHub/Link/Route.php
> +    public function __construct($router, $routeName, $routeParams, $name, $zoneIdentifier)
Typehint for `$router` (which should be renamed to `$urlGenerator`) against `UrlGeneratorInterface`

2017-05-04 11:32 UTC, andrerom commented on src/lib/Components/NavigationHub.php
> +                'tag' => self::TAG_NAME,
> Note that self will be deprecated soon in PHP

hmm, can't find any rfc about that

2017-05-04 12:19 UTC, lolautruche commented on src/lib/Components/NavigationHub.php
> +                'tag' => self::TAG_NAME,
I saw that somewhere a while ago. But maybe it didn't even go into a RFC...

2017-05-04 12:20 UTC, lolautruche commented on src/lib/Components/NavigationHub.php
> +                'tag' => self::TAG_NAME,
But in any case `static` should always be preferred to `self` as it's way more flexible, without significant impact on performance

2017-05-04 13:55 UTC, bdunogier commented on src/lib/EventSubscriber/AppRendererSubscriber.php
> +        $this->appRenderer->render($event->getResponse(), $this->app);
Neither, it renders the app into the `given Response()`.

2017-05-04 13:56 UTC, bdunogier commented
Thank you for the feedback @lolautruche, I'll take care of it.

2017-05-05 11:20 UTC, bdunogier commented on src/bundle/Resources/config/navigationhub.yml
> +    ezsystems.platformui.navigationhub.link.subtree.class: EzSystems\HybridPlatformUi\NavigationHub\Link\Subtree
Those parameters are used by multiple services.

2017-05-05 11:24 UTC, bdunogier commented on src/lib/App/RequestAppResponseRenderer.php
> +        $appResponse = $this->ajaxUpdateRequestMatcher->matches($this->requestStack->getMasterRequest())
In which other files does this apply ? As far as I can tell, this is the only injection of `@master_request`; the other cases are EventSubscribers that get the Request from the Event, afaict.

2017-05-05 13:18 UTC, lolautruche requested changes
I added "master request ping" where you can inject it

2017-05-05 13:18 UTC, lolautruche commented on src/lib/Components/Browse.php
> +        $this->request = $stack->getMasterRequest();
master request ping

2017-05-05 13:18 UTC, lolautruche commented on src/lib/Components/NavigationHub.php
> +        $this->request = $stack->getMasterRequest();
master request ping

2017-05-05 15:32 UTC, dpobel approved these changes
besides my small remarks and @lolautruche ones, I think this is mostly ok and we should try to merge that soon, that way, we (I :)) can do additional clean up and start integrating hybrid-platform-ui-core-components and `<ez-subitem>` that is being implemented in PlatformUIBundle.

2017-05-05 15:32 UTC, dpobel commented on INSTALL.md
> +        "dpobel/ez-field-edit": "dev-master as 1.0.x-dev",
this is a bit outdated, only composer/installers (and the corresponding repository) is now needed. But maybe, we should tell people to use the branch of https://github.com/ezsystems/ezplatform/pull/177 ?

2017-05-05 15:32 UTC, dpobel commented on composer.json
> +            "url": "https://github.com/dpobel/ez-field-edit.git"
let's remove those repositories (as stated above, only https://github.com/dpobel/installers.git is needed)

2017-05-05 15:32 UTC, dpobel commented on src/bundle/Resources/public/webcomponents/ez-main-content.html
> +<link rel="import" href="../../../assets/ezplatform/ez-field-edit/ez-field-edits.html">
together with dpobel/ez-field-edit you should remove this import and the following one (as well as the comment above)

2017-05-05 15:32 UTC, dpobel commented on src/bundle/Resources/public/webcomponents/ez-main-content.html
> +        constructor() {
and given the Content Edit Form is not yet there, all the method from `constructor` to `_getContentEditForm` can be removed as well

2017-05-05 15:32 UTC, dpobel commented on src/bundle/Resources/views/locationview.html.twig
> +    <a href="{#{ path('proto_draft_create', {contentId: location.contentInfo.id}) }#}">Edit this content</a>
I guess you should just remove that paragraph :)

2017-05-05 17:10 UTC, bdunogier commented on INSTALL.md
> +        "dpobel/ez-field-edit": "dev-master as 1.0.x-dev",
Good catch @dpobel. It was indeed meant as a temporary workaround, the branch replaces it.

2017-05-05 17:14 UTC, bdunogier commented on src/bundle/Resources/views/locationview.html.twig
> +    <a href="{#{ path('proto_draft_create', {contentId: location.contentInfo.id}) }#}">Edit this content</a>
Indeed. While at it, I have added the basic code that iterates over the fields and displays them :)

2017-05-05 17:18 UTC, bdunogier commented
All remarks should have been fixed besides the one about `src/lib/Components/*`. They can be taken care of later, as they're on very early pieces that will be reworked anyway.

2017-05-06 09:59 UTC, bdunogier commented on src/lib/EventSubscriber/AppRendererSubscriber.php
> +        $this->appRenderer->render($event->getResponse(), $this->app);
Could be changed to renderComponentToResponse, maybe. In which case it might duplicate another renderer. Worth checking out.

2017-05-06 10:31 UTC, bdunogier commented
Squashing as we are now green.

2017-05-09 20:40 UTC, merged