Added PHP CS Fixer configuration
ezsystems/hybrid-platform-ui pull request #24
Opened 2017-06-19 16:56 UTC by bdunogier

Title says it all.

2017-06-19 16:57 UTC, bdunogier commented
@andrerom how do we enable ezrobot for this ?

2017-06-19 18:09 UTC, andrerom requested changes

2017-06-19 18:09 UTC, andrerom commented on .php_cs
> +    // PHP-CS-Fixer 1.x syntax (deprecated)
don't need this, we only support one version and that is 2.x. the if cases where just needed during transition from 1.x ot 2.x

2017-06-19 18:10 UTC, andrerom commented
> @andrerom how do we enable ezrobot for this ?

you create a new job on jenkins, @vidarl might be able to show you how :)

2017-06-20 09:43 UTC, andrerom approved these changes

2017-06-20 09:43 UTC, andrerom commented
+1 assuming it passes ;)

2017-06-20 15:29 UTC, bdunogier commented
Okay, php-cs-fixer passed, merging

2017-06-20 15:29 UTC, merged