use inheritance over decoration for locations
ezsystems/hybrid-platform-ui pull request #36
Opened 2017-06-23 14:52 UTC by mcurran-inviqa

2017-06-23 15:03 UTC, bdunogier requested changes
I think I like this version better.

Could you try to convince git that `DecoratedLocation` was _renamed_ to `UiLocation` (instead of delete / create) ?

2017-06-23 15:03 UTC, bdunogier commented on src/lib/Repository/Values/Content/UiLocation.php
> +    public function __construct(array $properties = [], Location $location)
`$location` needs to be made first, as it is not optional. It also feels more correct :)

2017-06-23 15:03 UTC, bdunogier commented on src/lib/Repository/UiLocationService.php
> +        $locationService = $this->locationService;
I wouldn't create local var for properties. `$this` doesn't really complexify the code.

2017-06-23 15:11 UTC, mcurran-inviqa commented on src/lib/Repository/UiLocationService.php
> +        $locationService = $this->locationService;
it's because it's passed into another function and is no longer in scope.

2017-06-23 15:30 UTC, bdunogier approved these changes
Works for me. @maxbaldanza ?

2017-06-23 15:32 UTC, maxbaldanza approved these changes
LGTM 👍

2017-06-23 15:52 UTC, bdunogier commented
Pushed a couple changes to the PR.

As for typehinting, we need to typehint on the API classes & interfaces, _not Core_.

And as for `$this` inside anonymous functions, it was added in PHP 5.4.

2017-06-23 15:54 UTC, maxbaldanza requested changes

2017-06-23 15:54 UTC, maxbaldanza commented on src/lib/Repository/Values/Content/UiLocation.php
> +     * @var \eZ\Publish\API\Repository\Values\Content\Location[]
Could you not use `APILocation` here instead as it's already imported?

2017-06-24 22:24 UTC, bdunogier commented on src/lib/Repository/Values/Content/UiLocation.php
> +     * @var \eZ\Publish\API\Repository\Values\Content\Location[]
We tend to use the FQN in PhpDoc. When you're not using a smart IDE, for instance when reviewing code, it can be really helpful.

2017-06-26 07:45 UTC, bdunogier commented on src/lib/Repository/UiLocationService.php
> +    private function makeUiLocations(array $locations, ContentInfo $contentInfo)
I'd prefer `buildUiLocations`, for consistency with the kernel.

2017-06-26 11:36 UTC, maxbaldanza approved these changes

2017-06-26 11:56 UTC, merged