EZP-27443: Display main content tab
ezsystems/hybrid-platform-ui pull request #37
Opened 2017-06-23 15:32 UTC by maxbaldanza

https://jira.ez.no/browse/EZP-27443

<img width="1035" alt="screen shot 2017-06-23 at 15 18 00" src="https://user-images.githubusercontent.com/2786820/27489124-51d1790a-5831-11e7-98e5-f5c25ceac9bf.png">

2017-06-26 09:48 UTC, bdunogier requested changes

2017-06-26 09:48 UTC, bdunogier commented on src/bundle/Resources/views/content/tabs/content.html.twig
> +{% for contentTypeGroup in contentType.contentTypeGroups %}
Not the right element :-)

This is the group(s) the Content Type is part of. You want to iterate on the FieldDefinitions groups, that can be accessed with `$fieldDefinition->fieldGroup`.

You can use `@ezpublish.fields_groups.list` to get the human readable strings (uses translations).

2017-06-26 09:48 UTC, bdunogier commented
Unfortunately, large changes are required, since the wrong domain objects were used.

2017-06-26 09:58 UTC, maxbaldanza commented on src/bundle/Resources/views/content/tabs/content.html.twig
> +{% for contentTypeGroup in contentType.contentTypeGroups %}
🤔 if you look at `UiContentType:: getFieldDefinitionsByFieldGroup` I am using the `$fieldDefinition->fieldGroup` I thought the translated string could be obtained from the content type but I shall take a look at the mentioned service 👍

2017-06-26 12:18 UTC, dpobel commented on src/bundle/Resources/views/content/tabs/content.html.twig
> +    <section class="ez-fieldgroups ez-fieldgroup ez-fieldgroup">
too many classes from v1 here :)
For now, the following markup should be enough:
```html
<section class="ez-fieldgroup">
    <h3 class="ez-fieldgroup-name">{{ fieldgroupName }}</h3>
    <!-- fields here -->
</section>
```

2017-06-27 15:34 UTC, bdunogier requested changes

2017-06-27 15:34 UTC, bdunogier commented on src/lib/Repository/UiFieldGroupService.php
> +            $fieldsInGroup = array_filter($fields, function (FieldDefinition $field) use ($groupId) {
Would you mind refactoring this part to a private method ? It has quite a lot of logic and not much explanations. Something like `$fieldsInGroup = filterFieldsFromGroup($fields, $groupId);`.

2017-06-27 17:01 UTC, dpobel approved these changes

2017-06-27 23:02 UTC, bdunogier approved these changes

2017-06-27 23:04 UTC, merged