[WIP] Services autowiring
ezsystems/hybrid-platform-ui pull request #43
Opened 2017-06-28 14:46 UTC by bdunogier

> Status: work in progress

Integrates auto-wiring to the package's services.

For classes that inherit from a common interface, such as `RequestMatcherInterface`, an intermediate interface is required to get autowiring to work in a natural way.

Example:
```
class PjaxRequestMatcher implements RequestMatcherInterface { }
```

```
interface PjaxRequestMatcher extends RequestMatcherInterface { }

class HeaderPjaxRequestMatcher implements PjaxRequestMatcher { }
```

2017-06-29 09:01 UTC, mcurran-inviqa commented on src/lib/View/AppConfigCoreViewMainContentMapper.php
> +     * @param \eZ\Publish\Core\MVC\Symfony\View\View $view
could probably use inheritDoc here

2017-06-29 09:16 UTC, mcurran-inviqa requested changes

2017-06-29 09:16 UTC, mcurran-inviqa commented on src/lib/View/CoreViewMainContentMapper.php
> +interface CoreViewMainContentMapper extends MainContentMapper
Docblock?

2017-06-29 09:16 UTC, mcurran-inviqa commented on src/lib/Http/HybridRequestMatcher.php
> +
Docblock?

2017-06-29 09:16 UTC, mcurran-inviqa commented on src/lib/Http/FormatAttributeHtmlFormatRequestMatcher.php
> +
This class name is slightly confusing it sounds like a combination of a method and a class name

2017-06-29 09:16 UTC, mcurran-inviqa commented on src/lib/Http/AdminRequestMatcher.php
> +
this is defined in parent interface?

2017-06-29 09:46 UTC, bdunogier commented on src/lib/Http/FormatAttributeHtmlFormatRequestMatcher.php
> +
Well, it may sound like it, but "format" is a noun in that case (the "format" request attribute). Do you have an alternative in mind.

2017-06-29 09:53 UTC, mcurran-inviqa commented on src/lib/Http/FormatAttributeHtmlFormatRequestMatcher.php
> +
a docblock may suffice here to remove the confusion

2017-06-30 08:53 UTC, bdunogier commented
Taken care of your comments @mcurran-inviqa. Better ?

2017-06-30 12:30 UTC, bdunogier commented on src/lib/View/AppConfigCoreViewMainContentMapper.php
> +     * @param \eZ\Publish\Core\MVC\Symfony\View\View $view
The doc is supposed to be inherited from the parent without the need for `inheritDoc`.

2017-06-30 12:41 UTC, maxbaldanza reviewed
There's a few new files been added here do they not need the copyright notice adding?

2017-06-30 12:53 UTC, mcurran-inviqa approved these changes

2017-06-30 16:25 UTC, merged