EZP-27567: Allow deletion of archived versions
ezsystems/hybrid-platform-ui pull request #52
Opened 2017-07-04 09:07 UTC by maxbaldanza

https://jira.ez.no/browse/EZP-27567

2017-07-04 09:27 UTC, bdunogier approved these changes

2017-07-04 09:46 UTC, bdunogier commented
Not a huge fan of how this is factored, but it is consistent with what exists, and can be improved later.

2017-07-04 14:02 UTC, bdunogier requested changes

2017-07-04 14:02 UTC, bdunogier commented on src/bundle/Controller/VersionController.php
> +    protected function redirectUser(RouterInterface $router, $contentId)
I'd prefer `redirectToContentView()`.

2017-07-04 14:06 UTC, bdunogier commented on src/bundle/Resources/config/routing.yml
> +    path: /version/archive-actions/{contentId}
I'd rather have `content` in the URI.
Maybe `/content/{contentId}/versions/archives` ?

2017-07-06 13:37 UTC, bdunogier approved these changes

2017-07-06 13:37 UTC, bdunogier commented
@mcurran-inviqa can you also review this please ?

2017-07-06 15:16 UTC, mcurran-inviqa approved these changes

2017-07-06 23:29 UTC, merged