EZP-27476: app symfony error handling
ezsystems/hybrid-platform-ui pull request #68
Opened 2017-07-07 18:02 UTC by bdunogier

> Status: WIP
> [JIRA](https://jira.ez.no/browse/EZP-27476)

### TODO
- [ ] Specs
- [ ] Finalize full page rendering of exceptions
- [ ] Remove test commit

2017-07-10 09:41 UTC, dpobel requested changes

2017-07-10 09:41 UTC, dpobel commented on src/lib/App/RequestAppResponseRenderer.php
> +            'type' => 'error',
I think we need a `Notification` value object (I know this collides with #67)

2017-07-10 09:41 UTC, dpobel commented on src/lib/Components/Component.php
>      public function __toString();
I think you can remove `__toString` from this interface and remove `__toString` implementation in components implementing this interface

2017-07-10 09:41 UTC, dpobel commented on src/lib/Components/NavigationHub.php
> +    public function __construct(EngineInterface $templating, Request $request = null, array $zones = [], array $links = [])
is there a reason to add a default value to `$request` ?

2017-07-10 09:41 UTC, dpobel commented on src/lib/Components/App.php
> +        return count($this->notifications) === 1
that does not seem super reliable :) Maybe you can set a property on the app in `RequestAppResponseRenderer::configureAppException`

2017-07-10 12:14 UTC, bdunogier commented on src/lib/Components/App.php
> +        return count($this->notifications) === 1
The todo list for the PR agrees with you: _Verify that the app exception rendering based on 1 error notification is sufficient and doesn't have unwanted side effects_ :)

2017-07-10 12:21 UTC, bdunogier commented on src/lib/Components/Component.php
>      public function __toString();
Indeed.

2017-07-10 12:22 UTC, bdunogier commented on src/lib/Components/NavigationHub.php
> +    public function __construct(EngineInterface $templating, Request $request = null, array $zones = [], array $links = [])
Yes, `Fixed an error with Request when using debug:event-dispatcher`. CLI doesn't like the Request as a required service ctor argument.

2017-07-11 17:32 UTC, bdunogier commented on src/lib/Components/App.php
> +        return count($this->notifications) === 1
Fixed now. Added an `exception` property to the app, that if is set will trigger the exception rendering.

2017-07-11 17:32 UTC, bdunogier commented on src/lib/Components/Component.php
>      public function __toString();
Done.

2017-07-11 17:32 UTC, bdunogier commented on src/lib/App/RequestAppResponseRenderer.php
> +            'type' => 'error',
Indeed.

2017-07-21 07:58 UTC, dpobel approved these changes
I like the idea of the Notifications component :)

2017-07-21 08:01 UTC, bdunogier commented
> I like the idea of the Notifications component :)

Well, it was the clean alternative to having the component render itself. I'm still not a big fan of the components being Injectables as well as receiving values, but at least the Notifications component is consistently wrong ;)

2017-07-21 09:00 UTC, merged