EZP-27568: Create draft from an archived version.
ezsystems/hybrid-platform-ui pull request #69
Opened 2017-07-10 10:36 UTC by maxbaldanza

- [x] Create draft from an archived version.
- [x] Validate form so that only one version can be selected when creating a new draft. Any number of versions can be selected when deleting.

https://jira.ez.no/browse/EZP-27568

2017-07-10 12:23 UTC, glye commented on src/lib/Repository/UiVersionService.php
> +     * Creates a new draft based on the content and verisionNo.
versionNo

2017-07-10 12:50 UTC, mcurran-inviqa approved these changes

2017-07-10 12:50 UTC, bdunogier requested changes
I'm overall a bit unsure about falling back to id as arguments.

Our Repository's API is on purpose mostly manipulating Value Objects, and I think that we should, when we can, use them instead of scalards in this layer as well.

2017-07-10 12:50 UTC, bdunogier commented on src/lib/Repository/UiVersionService.php
> +            $this->loadContentInfo($contentId),
You can use `$contentInfo` from above. And I don't think it's worth wrapping that line then.

2017-07-10 12:50 UTC, bdunogier commented on src/lib/Repository/UiVersionService.php
> +     * Creates a new draft based on the content and verisionNo.
Typo: `versionNo`.

2017-07-10 12:50 UTC, bdunogier commented on src/lib/Repository/UiVersionService.php
> +     * Creates a new draft based on the content and versionNo.
`contentId`, actually.

2017-07-10 12:50 UTC, bdunogier commented on src/bundle/Controller/VersionController.php
> +            $this->createDraftVersionBasedOnFormSubmit($archiveActionsForm, $content->id);
Given that you have a `Content`, is it really worth passing the ID ? It is gonna be loaded back to a `ContentInfo` later on. You might as well pass the `ContentInfo` directly.

2017-07-11 09:26 UTC, mcurran-inviqa commented on src/bundle/Form/Versions/ArchivedActions.php
> +                'validation_groups' => false,
use [] syntax for consistency

2017-07-11 09:53 UTC, mcurran-inviqa approved these changes

2017-07-12 11:06 UTC, bdunogier approved these changes

2017-07-12 11:28 UTC, merged