EZP-27615: If user does not have permission to view versions display message
ezsystems/hybrid-platform-ui pull request #71
Opened 2017-07-12 09:06 UTC by maxbaldanza

https://jira.ez.no/browse/EZP-27615

![screen shot 2017-07-12 at 09 39 36](https://user-images.githubusercontent.com/2786820/28110224-8d4d1748-66e9-11e7-81b2-44d43084042d.png)

2017-07-12 11:43 UTC, bdunogier commented
Should the buttons ("New draft based on select version", "Delete") be hidden when there are no versions displayed ?

2017-07-12 12:22 UTC, maxbaldanza commented
Not according to the mock up on the ticket although I think this may be a little weird and have said the same thing on the ticket: https://jira.ez.no/browse/EZP-27615

2017-07-12 14:59 UTC, maxbaldanza commented
@bdunogier buttons are now disabled as requested by @SylvainGuittard

2017-07-12 15:45 UTC, SylvainGuittard commented
thanks @maxbaldanza

2017-07-13 23:38 UTC, bdunogier requested changes
The way the supplier's data is used in the controller really annoys me. Please try to think of a better approach to this.

2017-07-13 23:38 UTC, bdunogier commented on src/bundle/Controller/VersionController.php
> +            $view->hasParameter('draftVersions') ? $view->getParameter('draftVersions') : []
I really don't like that way of reusing what the supplier will hopefully set. There is no contract with the interface that certifies any of that.

2017-07-14 09:37 UTC, maxbaldanza commented on src/bundle/Controller/VersionController.php
> +            $view->hasParameter('draftVersions') ? $view->getParameter('draftVersions') : []
🤔 not sure there is a better approach without breaking the interface. Did you have something else in mind?
Our views assume that these values are set so isn't it safe for our forms to do the same?

2017-07-19 12:26 UTC, bdunogier approved these changes

2017-07-19 12:27 UTC, merged