EZP-27579 add breadcrumbs to content view
ezsystems/hybrid-platform-ui pull request #77
Opened 2017-07-13 12:25 UTC by maxbaldanza

- [X] Move loading locations to ParameterSupplier so that it can be used for loading the breadcrumbs.
- [X] Add breadcrumbs to content view

https://jira.ez.no/browse/EZP-27579

![screen shot 2017-07-13 at 13 22 56](https://user-images.githubusercontent.com/2786820/28166082-7d187666-67ce-11e7-85fc-4dd9632c46ac.png)

2017-07-13 15:18 UTC, dpobel requested changes

2017-07-13 15:18 UTC, dpobel commented on src/bundle/Resources/views/locationview.html.twig
> +                {{ include('@EzSystemsHybridPlatformUi/fields/location/path.html.twig', {'locations': location.pathLocations}) }}
put that in the `header` below and before the `h1`

2017-07-13 23:32 UTC, bdunogier approved these changes
Not a huge fan, but it gets the job done. The suppliers look a bit superfluous in this implementation.

2017-07-13 23:32 UTC, bdunogier commented on src/bundle/Controller/LocationController.php
> +                $view->hasParameter('locations') ? $view->getParameter('locations') : []
I understand why you would reuse that value, but it really feels like a sever break of responsibilities.

2017-07-17 10:14 UTC, mcurran-inviqa approved these changes

2017-07-17 15:48 UTC, bdunogier approved these changes

2017-07-17 15:49 UTC, merged