EZP-27448 url aliases tab
ezsystems/hybrid-platform-ui pull request #78
Opened 2017-07-17 09:05 UTC by mcurran-inviqa

- adds url controller
- adds paramter suppliers for urls
- adds view only url aliases tab

![image](https://user-images.githubusercontent.com/5628533/28261486-67458a3e-6ad7-11e7-82bf-6e7160c07569.png)

2017-07-17 10:14 UTC, maxbaldanza approved these changes

2017-07-17 10:24 UTC, dpobel requested changes

2017-07-17 10:24 UTC, dpobel commented on src/bundle/Resources/views/content/tabs/urls.html.twig
> +                    <a href="{{ customUrl.path }}">{{ customUrl.path }}</a>
according to description in https://jira.ez.no/browse/EZP-27448, this is not supposed to be a link (which leads to a different siteaccess btw)

2017-07-17 14:14 UTC, dpobel approved these changes

2017-07-18 18:50 UTC, bdunogier commented
When the same URL alias is shared by multiple languages, the lines are supposed to be merged.

2017-07-19 09:20 UTC, bdunogier approved these changes

2017-07-19 09:20 UTC, merged